from chat import gemini_bot
from difflib import SequenceMatcher
chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?",
    "Làm thế nào để đối phó với stress?",
    "Làm thế nào để học tốt một ngôn ngữ mới?",
    "Các phương pháp học tập hiệu quả nhất là gì?",
    "Bạn có thể gợi ý một số sách hay cho việc tự học không?",
    "Làm thế nào để tăng cường khả năng tập trung trong học tập?",
    "Các lợi ích của việc học trực tuyến là gì?",
    "Làm thế nào để phát triển tư duy phản biện?",
    "Làm thế nào để quản lý thời gian học tập hiệu quả?"
    "Làm thế nào để tăng lượt theo dõi trên Instagram?",
    "Những xu hướng phổ biến trên TikTok hiện nay là gì?",
    "Làm sao để bảo mật tài khoản Facebook?",
    "Cách tốt nhất để quảng cáo trên Twitter là gì?",
    "Threads là gì và cách sử dụng như thế nào?",
    "Làm thế nào để xây dựng một trang cá nhân hấp dẫn trên LinkedIn?",
    "Cách tạo nội dung hấp dẫn trên YouTube là gì?",
    "Làm sao để tăng cường tương tác trên mạng xã hội?",
    "Các cách hiệu quả để quản lý nhiều tài khoản mạng xã hội là gì?",
    "Những ưu điểm và nhược điểm của các nền tảng mạng xã hội phổ biến là gì?"
    "Làm thế nào để tạo nội dung chất lượng cao?",
    "Các loại nội dung nào phổ biến nhất trên internet?",
    "Các thể loại game phổ biến hiện nay là gì?",
    "Nhà phát triển game nổi tiếng nào đã tạo ra tựa game 'The Witcher'?",
    "Những game nổi tiếng nào hiện đang thịnh hành trên thị trường?",
    "Nhân vật nổi tiếng trong series game 'Final Fantasy' là ai?",
    "Tựa game 'The Legend of Zelda' được phát triển bởi công ty nào?",
    "Thể loại game FPS là gì và một vài ví dụ tiêu biểu?",
    "Làm thế nào để chọn game phù hợp với sở thích của mình?",
    "Những tựa game nào có cốt truyện hay nhất?",
    "Nhân vật chính của game 'Super Mario' là ai?",
    "Các tựa game nổi tiếng do nhà phát triển FromSoftware sản xuất là gì?"
    "Những streamer nổi tiếng nhất Việt Nam là ai?",
    "Ai là streamer nổi tiếng trên Twitch với lượng theo dõi lớn nhất thế giới?",
    "Những nền tảng nào phổ biến để stream game?",
    "Các streamer nổi tiếng là ai?",
    "Làm thế nào để thu hút người xem khi stream?",
    "Những thiết bị cần thiết cho một setup stream cơ bản là gì?",
    "Ai là streamer nổi tiếng với tựa game 'League of Legends'?",
    "Làm thế nào để tương tác hiệu quả với khán giả trong khi stream?"
    "Những món ăn đặc sản nổi tiếng của Việt Nam là gì?",
    "Các loại sushi phổ biến là gì?",
    "Thực phẩm nào tốt cho sức khỏe tim mạch?",
    "Bạn có thể gợi ý một vài món ăn chay ngon không?",
    "Món ăn đường phố nào nổi tiếng nhất thế giới?",
    "Làm thế nào để nhận biết thực phẩm hữu cơ?",
    "Các món ăn nổi tiếng của ẩm thực Pháp là gì?",
    "Làm thế nào để bảo quản rau củ quả tươi lâu?",
    "Những loại trái cây nào chứa nhiều vitamin C?",
    "Món tráng miệng nào phổ biến trong ẩm thực Ý?"
    "Cách làm món phở bò ngon là gì?",
    "Các kỹ thuật cơ bản trong nấu ăn là gì?",
    "Làm thế nào để làm bánh mì tại nhà?",
    "Bạn có thể gợi ý một vài công thức nấu ăn đơn giản cho người mới bắt đầu không?",
    "Cách làm nước sốt spaghetti ngon là gì?",
    "Làm thế nào để làm sushi tại nhà?",
    "Các phương pháp nấu nướng nào giữ nguyên dưỡng chất trong thực phẩm?",
    "Làm thế nào để làm món gà rán giòn tan?",
    "Cách làm món salad trộn đơn giản nhưng ngon miệng là gì?"
    "Những hoạt động giải trí phổ biến nhất hiện nay là gì?",
    "Làm thế nào để chọn một bộ phim hay để xem?",
    "Các trò chơi giải trí nào được yêu thích nhất?",
    "Bạn có thể gợi ý một vài cách thư giãn sau một ngày làm việc căng thẳng không?",
    "Những sự kiện giải trí lớn trong năm nay là gì?",
    "Các cách giải trí cho gia đình và bạn bè là gì?",
    "Làm thế nào để tìm kiếm các hoạt động giải trí mới lạ?",
    "Các ứng dụng giải trí phổ biến hiện nay là gì?",
    "Bạn có thể chia sẻ một số mẹo để tổ chức một bữa tiệc thành công không?",
    "Làm thế nào để giữ cho cuộc sống giải trí luôn phong phú?"
    "Các thể loại âm nhạc phổ biến hiện nay là gì?",
    "Ai là nghệ sĩ nổi tiếng nhất thế giới hiện nay?",
    "Làm thế nào để chọn nhạc phù hợp cho một bữa tiệc?",
    "Những album nhạc hay nhất của thập kỷ qua là gì?",
    "Các công cụ và phần mềm nào hữu ích cho việc sáng tác âm nhạc?",
    "Làm thế nào để học chơi một nhạc cụ mới?",
    "Những xu hướng âm nhạc mới nhất hiện nay là gì?",
    "Ai là những ca sĩ nổi tiếng trong lịch sử âm nhạc?",
    "Những lễ hội âm nhạc lớn trên thế giới là gì?"
    "Những bộ phim hay nhất của năm nay là gì?",
    "Làm thế nào để chọn phim phù hợp với tâm trạng của bạn?",
    "Ai là đạo diễn nổi tiếng trong ngành điện ảnh?",
    "Các thể loại phim phổ biến hiện nay là gì?",
    "Những phim hoạt hình nổi tiếng dành cho cả gia đình là gì?",
    "Các phim kinh điển mà bạn nên xem ít nhất một lần là gì?",
    "Làm thế nào để phân biệt phim hay và phim dở?",
    "Những diễn viên nổi tiếng nhất hiện nay là ai?",
    "Các nền tảng xem phim trực tuyến phổ biến là gì?",
    "Những bộ phim dựa trên sách nổi tiếng là gì?"
    "Những bộ truyện tranh nổi tiếng nhất hiện nay là gì?",
    "Các thể loại truyện tranh phổ biến là gì?",
    "Ai là tác giả nổi tiếng trong ngành truyện tranh?",
    "Những bộ truyện tranh kinh điển mà bạn nên đọc là gì?",
    "Các nhà xuất bản truyện tranh nổi tiếng là gì?",
    "Truyện tranh Nhật Bản (manga) khác gì so với truyện tranh phương Tây?",
    "Những ngôn ngữ lập trình phổ biến nhất hiện nay là gì?",
    "Làm thế nào để bắt đầu học lập trình từ con số không?",
    "Các công cụ và phần mềm hữu ích cho lập trình viên là gì?",
    "Làm thế nào để giải quyết vấn đề khi gặp lỗi trong mã nguồn?",
    "Những kỹ năng cần thiết để trở thành lập trình viên giỏi là gì?",
    "Các phương pháp quản lý dự án phần mềm hiệu quả là gì?",
    "Làm thế nào để viết mã sạch và dễ bảo trì?",
    "Những thách thức lớn nhất trong ngành lập trình hiện nay là gì?",
    "Làm thế nào để giữ kỹ năng lập trình của bạn luôn cập nhật?",
    "Các chứng chỉ và khóa học cần thiết cho lập trình viên là gì?"
    "Những bước cơ bản để viết một kịch bản là gì?",
    "Làm thế nào để phát triển một cốt truyện hấp dẫn?",
    "Các yếu tố quan trọng trong việc xây dựng nhân vật là gì?",
    "Làm sao để tạo ra các cuộc đối thoại tự nhiên trong kịch bản?",
    "Những công cụ và phần mềm hữu ích cho viết kịch bản là gì?",
    "Những kỹ năng mềm quan trọng nào cần được phát triển trong môi trường đại học?",
    "Cách chọn trường đại học phù hợp với sở thích và khả năng của bản thân?",
    "Những xu hướng giáo dục hiện tại trong các trường đại học là gì?",
    "Làm thế nào để đối phó với căng thẳng học tập trong thời gian thi cử?",
    "Có những chương trình học bổng nào dành cho sinh viên tại các trường đại học Việt Nam?",
    "Những dịch vụ y tế cơ bản mà một bệnh viện công lập ở Việt Nam cung cấp là gì?",
    "Cách chọn bác sĩ phù hợp cho các vấn đề sức khỏe của bạn?",
    "Những bước cần thực hiện để đăng ký bảo hiểm y tế tại các cơ sở y tế ở Việt Nam?",
    "Làm thế nào để chuẩn bị cho một cuộc kiểm tra sức khỏe định kỳ?",
    "Các cơ sở y tế tư nhân có ưu điểm gì so với bệnh viện công?",
    "Những tiến bộ mới nhất trong điều trị bệnh tiểu đường tại các cơ sở y tế ở Việt Nam là gì?",
    "Cách đối phó với tình trạng thiếu thuốc và thiết bị y tế tại các cơ sở y tế công?",
    "Những cơ sở y tế nổi tiếng tại các thành phố lớn ở Việt Nam là gì?",
    "Làm thế nào để lựa chọn dịch vụ chăm sóc sức khỏe tại nhà?",
    "Cách cải thiện chất lượng dịch vụ y tế tại các bệnh viện công lập ở Việt Nam?",
    "Những ngành nghề nào đang phát triển mạnh mẽ tại Việt Nam hiện nay?",
    "Làm thế nào để bắt đầu kinh doanh tại Việt Nam?",
    "Cách tìm kiếm nhà đầu tư cho dự án khởi nghiệp ở Việt Nam?",
    "Những yếu tố nào ảnh hưởng đến sự thành công của một doanh nghiệp nhỏ tại Việt Nam?",
    "Các cơ hội và thách thức khi đầu tư vào thị trường Việt Nam là gì?",
    "Làm thế nào để thực hiện chiến lược marketing hiệu quả cho doanh nghiệp tại Việt Nam?",
    "Những thủ tục pháp lý cần thiết khi thành lập một công ty ở Việt Nam?",
    "Các doanh nghiệp công nghệ nổi bật ở Việt Nam là gì?",
    "Trường phổ thông nào ở Hà Nội có chương trình giảng dạy tiếng Anh chất lượng cao?",
    "Những trường đại học hàng đầu ở TP.HCM cho ngành công nghệ thông tin là gì?",
    "Đại học Quốc gia Hà Nội cung cấp những chuyên ngành gì cho sinh viên quốc tế?",
    "Đại học Sài Gòn có các chương trình đào tạo nào cho sinh viên nước ngoài?",
    "Bệnh viện nào ở Hà Nội nổi tiếng với dịch vụ chăm sóc sức khỏe tim mạch?",
    "Những phòng khám tư nhân uy tín ở TP.HCM cho điều trị da liễu là gì?",
    "Bệnh viện Đà Nẵng có các dịch vụ nào cho bệnh nhân quốc tế?",
    "Những cơ sở y tế hàng đầu ở Cần Thơ cho điều trị ung thư là gì?",
    "Bệnh viện nào ở Nha Trang có dịch vụ khám sức khỏe tổng quát chất lượng?",
    "Cơ sở y tế nào ở Huế nổi bật trong việc điều trị bệnh nhi?",
    "Bệnh viện nào ở Bình Dương có dịch vụ cấp cứu tốt nhất?",
    "Các cơ sở y tế nào ở Quảng Ninh cung cấp dịch vụ sinh sản và hiếm muộn?",
    "Bệnh viện nào ở TP.HCM có dịch vụ phẫu thuật thẩm mỹ chất lượng cao?",
    "Đại học Khoa học Tự nhiên - ĐHQG Hà Nội có những ngành học nào nổi bật?",
    "Chương trình đào tạo ngành Khoa học Máy tính tại Đại học Khoa học Tự nhiên - ĐHQG Hà Nội được đánh giá như thế nào?",
    "Học phí tại Đại học Khoa học Tự nhiên - ĐHQG Hà Nội là bao nhiêu cho các ngành học khác nhau?",
    "Đại học Khoa học Tự nhiên - ĐHQG Hà Nội có các chương trình học bổng nào cho sinh viên?",
    "Các cơ hội nghiên cứu và thực tập tại Đại học Khoa học Tự nhiên - ĐHQG Hà Nội là gì?",
    "Đại học Khoa học Tự nhiên - ĐHQG Hà Nội có hợp tác quốc tế với các trường đại học nào không?",
    "Tỷ lệ tốt nghiệp và việc làm của sinh viên Đại học Khoa học Tự nhiên - ĐHQG Hà Nội là bao nhiêu?",
    "Đại học Khoa học Tự nhiên - ĐHQG Hà Nội có các câu lạc bộ hoặc tổ chức sinh viên nào nổi bật không?",
    "Cơ sở vật chất và trang thiết bị học tập tại Đại học Khoa học Tự nhiên - ĐHQG Hà Nội như thế nào?",
    "Quá trình tuyển sinh vào Đại học Khoa học Tự nhiên - ĐHQG Hà Nội gồm những bước nào?",
    "Đại học Khoa học Tự nhiên - ĐHQG Hà Nội có các chương trình đào tạo thạc sĩ và tiến sĩ không?",
    "Các ngành học nào tại Đại học Khoa học Tự nhiên - ĐHQG Hà Nội được đánh giá cao trong bảng xếp hạng đại học quốc gia?",
    "Chương trình đào tạo và nghiên cứu trong lĩnh vực môi trường tại Đại học Khoa học Tự nhiên - ĐHQG Hà Nội là gì?",
    "Đại học Khoa học Tự nhiên - ĐHQG Hà Nội có các chương trình trao đổi sinh viên với các trường quốc tế không?",
    "Các hoạt động ngoại khóa nào được tổ chức tại Đại học Khoa học Tự nhiên - ĐHQG Hà Nội?",
    "Đại học Khoa học Tự nhiên - ĐHQG Hà Nội có các dịch vụ hỗ trợ sinh viên như thế nào?",
    "Đại học Khoa học Tự nhiên - ĐHQG Hà Nội có các chương trình hợp tác với doanh nghiệp để hỗ trợ sinh viên tìm việc làm không?",
    "Các thành tựu nghiên cứu nổi bật của Đại học Khoa học Tự nhiên - ĐHQG Hà Nội trong những năm gần đây là gì?",
    "Làm thế nào để sinh viên tại Đại học Khoa học Tự nhiên - ĐHQG Hà Nội có thể tham gia vào các dự án nghiên cứu?"
]

def is_chitchat_question(user_question, sample_questions, threshold = 0.6):
    """
    Kiểm tra xem câu hỏi có phải là câu hỏi thông thường dựa trên sự tương đồng
    với các câu hỏi mẫu trong sample_questions.
    """
    for sample in sample_questions:
        similarity = SequenceMatcher(None, user_question.lower(), sample.lower()).ratio()
        if similarity >= threshold:
            return True
    return False

def handle_chitchat(user_question):
    respone = gemini_bot.response(user_question)
    return respone